name: Build OBS Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build pkg-config libglib2.0-dev libzip-dev
        sudo apt-get install -y libobs-dev obs-studio-dev
        
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install meson ninja pkg-config glib libzip
        brew install --cask obs
        
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install meson ninja pkgconfiglite
        
    - name: Build OpenTraceCapture
      run: |
        cd OpenTraceCapture
        meson setup builddir --buildtype=release
        meson compile -C builddir
        meson install -C builddir
        
    - name: Build Plugin
      run: |
        meson setup builddir --buildtype=release
        meson compile -C builddir
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: obs-measurement-overlay-${{ matrix.os }}
        path: builddir/
